automatically release to PyPI
appsembler/xblock-launchcontainer pull request #33
Opened 2019-04-08 16:35 UTC by thraxil

This configures TravisCI to automatically build and upload `sdist` and `bdist_wheel` packages to PyPI via our shared `appsembler` account.

Releases only go up when the change is pushed to the `master` branch (TravisCI default; you don't want random PRs to be able to trigger a release) with tags. The usual workflow for doing a release to PyPI then is to update the version in `setup.py`, etc. Merge it to `master`, tag a release locally (`git tag release-1.2.3`) then push that up with `git push --tags`.

2019-04-08 16:54 UTC, OmarIthawi approved these changes

2019-04-08 16:56 UTC, briandant requested changes
Many thanks for this, @thraxil! 

Would you mind adding your note from the PR description to the docs? Just something simple to be sure we understand precisely how the release process works.

2019-04-09 10:18 UTC, thraxil commented
@briandant done. It's going to be the same for multiple libraries, so I just made a Runbook entry in our wiki and link to that.

2019-04-09 10:18 UTC, OmarIthawi approved these changes
Readme changes are also good. Thanks!

2019-04-10 04:53 UTC, briandant approved these changes
Thanks, Anders!

2019-04-10 08:31 UTC, merged