add CODEOWNERS
appsembler/xblock-launchcontainer pull request #57
Opened 2021-11-09 09:36 UTC by thraxil

2021-11-16 21:38 UTC, bryanlandia requested changes
Suggested adding @briandant

2021-11-16 21:38 UTC, bryanlandia commented on .github/CODEOWNERS
> +* @bryanlandia
```suggestion
* @bryanlandia @briandant 
```

2021-12-02 18:28 UTC, briandant submitted a review, later dismissed

2021-12-02 18:29 UTC, briandant commented
@thraxil I saw a comment somewhere that for SOC 2 there should be only one code owner, is that right? https://appsembler.atlassian.net/wiki/spaces/ED/pages/2227503161/CODEOWNERS

2021-12-08 06:32 UTC, bryanlandia approved these changes

2021-12-08 08:25 UTC, merged